PROJECT_NAME=AVP-stagging

DEPLOY_PATH=D:/Xampp-Dont Delete/htdocs/AVP-stagging

BACKUP_PATH=D:/Xampp-Dont Delete/htdocs/backup

TEMP_DEPLOY_PATH=D:/Xampp-Dont Delete/htdocs/deployment-temp

PHP_PATH=D:/Software/Xampp-Dont Delete/php/

COMPOSER=C:/composer/composer.bat

MYSQL_PATH=D:/Xampp-Dont Delete/mysql/bin/mysql.exe

ENVIRONMENT=STAGING