PROJECT_NAME=AVP-stagging

DEPLOY_PATH=D:/Software/Xampp-Dont Delete/htdocs/AVP-stagging
BACKUP_PATH=D:/Software/Xampp-Dont Delete/htdocs/backup
TEMP_DEPLOY_PATH=D:/Software/Xampp-Dont Delete/htdocs/deployment-temp

EMAIL_TO=cdsdevopsteam@gmail.com, harivartthan.r@capdigisoft.net        //mail notifacation to this email address

PHP_PATH=D:/Software/Xampp-Dont Delete/php/php.exe
COMPOSER_PATH=C:/composer/composer.phar
MYSQL_PATH=D:/Software/Xampp-Dont Delete/mysql/bin/mysql.exe

ENVIRONMENT=STAGING