PROJECT_NAME=AVP-stagging

DEPLOY_PATH=D:/Xampp-org/htdocs/AVP-stagging

BACKUP_PATH=D:/Xampp-org/htdocs/backup

TEMP_DEPLOY_PATH=D:/Xampp-org/htdocs/deployment-temp

PHP_PATH=D:/Xampp-org/php/php.exe

COMPOSER=composer

ENVIRONMENT=STAGING